In [2]:
import pandas as pd
df=pd.read_csv('sample.txt',sep='\t',header=None)
df

     0        1       2   3           4          5
0  101    Arjun    Nair  25  9876543210      Kochi
1  102    Meera  Thomas  28  9845012345  Bengaluru
2  103    Rahul  Sharma  30  9123456789      Delhi
3  104    Priya   Menon  22  9745612390   Thrissur
4  105  Karthik    Iyer  27  9988776655    Chennai

In [3]:
df.columns=['ID','FName','LName','Age','Phone','Location']
df

    ID    FName   LName  Age       Phone   Location
0  101    Arjun    Nair   25  9876543210      Kochi
1  102    Meera  Thomas   28  9845012345  Bengaluru
2  103    Rahul  Sharma   30  9123456789      Delhi
3  104    Priya   Menon   22  9745612390   Thrissur
4  105  Karthik    Iyer   27  9988776655    Chennai

In [4]:
df.describe()

               ID       Age         Phone
count    5.000000   5.00000  5.000000e+00
mean   103.000000  26.40000  9.715880e+09
std      1.581139   3.04959  3.423484e+08
min    101.000000  22.00000  9.123457e+09
25%    102.000000  25.00000  9.745612e+09
50%    103.000000  27.00000  9.845012e+09
75%    104.000000  28.00000  9.876543e+09
max    105.000000  30.00000  9.988777e+09

In [5]:
df.shape

(5, 6)

In [6]:

df.dtypes

ID           int64
FName       object
LName       object
Age          int64
Phone        int64
Location    object
dtype: object

In [7]:
df1=df[['FName','LName','Age']]
df1.head(3)

   FName   LName  Age
0  Arjun    Nair   25
1  Meera  Thomas   28
2  Rahul  Sharma   30

In [9]:
df.isna().sum

<bound method DataFrame.sum of       ID  FName  LName    Age  Phone  Location
0  False  False  False  False  False     False
1  False  False  False  False  False     False
2  False  False  False  False  False     False
3  False  False  False  False  False     False
4  False  False  False  False  False     False>